;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
(defun botRepr000 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr001 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr002 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr010 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |________|  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr011 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |________|  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr012 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |________|  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr020 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr021 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr022 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr030 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr031 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr032 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr040 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr041 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr042 ()
	(format t "   0lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)

;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
;;; 1xx
(defun botRepr100 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|________|  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr101 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|________|  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr102 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|________|  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr110 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|________|  |________|  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr111 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|________|  |________|  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr112 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|________|  |________|  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr120 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     0lt    ~%")
	(format t "|________|  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr121 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     1lt    ~%")
	(format t "|________|  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr122 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     2lt    ~%")
	(format t "|________|  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr130 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|________|  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr131 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|________|  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr132 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|________|  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr140 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|________|  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr141 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|________|  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr142 ()
	(format t "   1lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|________|  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)

;;; 2xx
;;; 2xx
;;; 2xx
;;; 2xx
;;; 2xx
;;; 2xx
;;; 2xx
;;; 2xx
;;; 2xx
(defun botRepr200 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr201 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr202 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr210 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |        |     0lt    ~%")
	(format t "|        |  |________|  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr211 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |        |     1lt    ~%")
	(format t "|        |  |________|  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr212 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |        |     2lt    ~%")
	(format t "|        |  |________|  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr220 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |________|     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr221 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |________|     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr222 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|________|  |________|     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr230 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|________|  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr231 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|________|  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr232 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|________|  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr240 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|________|  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr241 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|________|  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr242 ()
	(format t "   2lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|________|  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)


;;; 3xx
;;; 3xx
;;; 3xx
;;; 3xx
;;; 3xx
;;; 3xx
;;; 3xx
;;; 3xx
(defun botRepr300 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr301 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr302 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr310 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |________|  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr311 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |________|  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr312 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |________|  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr320 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |________|     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr321 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |________|     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr322 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|________|  |        |            ~%")
	(format t "|        |  |________|     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr330 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|________|  |________|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr331 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|________|  |________|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr332 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|________|  |________|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr340 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|________|  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr341 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|________|  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr342 ()
	(format t "   3lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|________|  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
;;; 4xx
;;; 4xx
;;; 4xx
;;; 4xx
;;; 4xx
;;; 4xx
;;; 4xx
(defun botRepr400 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr401 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr402 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr410 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |________|  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr411 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |________|  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr412 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |________|  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr420 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr421 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr422 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr430 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr431 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr432 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr440 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr441 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr442 ()
	(format t "   4lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|        |                        ~%")
	(format t "|________|     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)

;;; 5xx
;;; 5xx
;;; 5xx
;;; 5xx
;;; 5xx
;;; 5xx
;;; 5xx
(defun botRepr500 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr501 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr502 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr510 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |________|  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr511 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |________|  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr512 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |________|  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr520 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr521 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr522 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr530 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr531 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr532 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr540 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr541 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr542 ()
	(format t "   5lt                            ~%")
	(format t "|        |    			         ~%")
	(format t "|________|                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)


;;; 6xx
;;; 6xx
;;; 6xx
;;; 6xx
;;; 6xx
;;; 6xx
;;; 6xx
(defun botRepr600 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr601 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr602 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr610 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |________|  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr611 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |________|  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr612 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |________|  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr620 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr621 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr622 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr630 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr631 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr632 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr640 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr641 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr642 ()
	(format t "   6lt                            ~%")
	(format t "|________|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)

;;; 7xx
;;; 7xx
;;; 7xx
;;; 7xx
;;; 7xx
;;; 7xx
;;; 7xx
(defun botRepr700 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr701 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr702 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     0lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr710 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |________|  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr711 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |________|  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr712 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     1lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |________|  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr720 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr721 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr722 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     2lt	             ~%")
	(format t "|        |  |        |            ~%")
	(format t "|        |  |________|     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr730 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr731 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr732 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     3lt	             ~%")
	(format t "|        |  |________|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr740 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     0lt    ~%")
	(format t "|        |  |        |  |        |~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr741 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     1lt    ~%")
	(format t "|        |  |        |  |________|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)
(defun botRepr742 ()
	(format t "   7lt                            ~%")
	(format t "|^^^^^^^^|    			         ~%")
	(format t "|        |                        ~%")
	(format t "|        |     4lt	             ~%")
	(format t "|        |  |^^^^^^^^|            ~%")
	(format t "|        |  |        |     2lt    ~%")
	(format t "|        |  |        |  |^^^^^^^^|~%")
	(format t "|________|  |________|  |________|~%")
	(format t " Bottle A    Bottle B    Bottle C~2%")
)

(defun ifFunction (arg1 arg2 arg3)
	(if (and (= arg1 0)(= arg2 0)(= arg3 0))
		(botRepr000)
		NIL
	)
	(if (and (= arg1 0)(= arg2 0)(= arg3 1))
		(botRepr001)
		NIL
	)
	(if (and (= arg1 0)(= arg2 0)(= arg3 2))
		(botRepr002)
		NIL
	)
	(if (and (= arg1 0)(= arg2 1)(= arg3 0))
		(botRepr010)
		NIL
	)
	(if (and (= arg1 0)(= arg2 1)(= arg3 1))
		(botRepr011)
		NIL
	)
	(if (and (= arg1 0)(= arg2 1)(= arg3 2))
		(botRepr012)
		NIL
	)
	(if (and (= arg1 0)(= arg2 2)(= arg3 0))
		(botRepr020)
		NIL
	)
	(if (and (= arg1 0)(= arg2 2)(= arg3 1))
		(botRepr021)
		NIL
	)
	(if (and (= arg1 0)(= arg2 2)(= arg3 2))
		(botRepr022)
		NIL
	)
	(if (and (= arg1 0)(= arg2 3)(= arg3 0))
		(botRepr030)
		NIL
	)
	(if (and (= arg1 0)(= arg2 3)(= arg3 1))
		(botRepr031)
		NIL
	)
	(if (and (= arg1 0)(= arg2 3)(= arg3 2))
		(botRepr032)
		NIL
	)
	(if (and (= arg1 0)(= arg2 4)(= arg3 0))
		(botRepr040)
		NIL
	)
	(if (and (= arg1 0)(= arg2 4)(= arg3 1))
		(botRepr041)
		NIL
	)
	(if (and (= arg1 0)(= arg2 4)(= arg3 2))
		(botRepr042)
		NIL
	)
	;;
	;;
	;;
	;;11111111111111111111
	;;
	;;
	;;
	(if (and (= arg1 1)(= arg2 0)(= arg3 0))
		(botRepr100)
		NIL
	)
	(if (and (= arg1 1)(= arg2 0)(= arg3 1))
		(botRepr101)
		NIL
	)
	(if (and (= arg1 1)(= arg2 0)(= arg3 2))
		(botRepr102)
		NIL
	)
	(if (and (= arg1 1)(= arg2 1)(= arg3 0))
		(botRepr110)
		NIL
	)
	(if (and (= arg1 1)(= arg2 1)(= arg3 1))
		(botRepr111)
		NIL
	)
	(if (and (= arg1 1)(= arg2 1)(= arg3 2))
		(botRepr112)
		NIL
	)
	(if (and (= arg1 1)(= arg2 2)(= arg3 0))
		(botRepr120)
		NIL
	)
	(if (and (= arg1 1)(= arg2 2)(= arg3 1))
		(botRepr121)
		NIL
	)
	(if (and (= arg1 1)(= arg2 2)(= arg3 2))
		(botRepr122)
		NIL
	)
	(if (and (= arg1 1)(= arg2 3)(= arg3 0))
		(botRepr130)
		NIL
	)
	(if (and (= arg1 1)(= arg2 3)(= arg3 1))
		(botRepr131)
		NIL
	)
	(if (and (= arg1 1)(= arg2 3)(= arg3 2))
		(botRepr132)
		NIL
	)
	(if (and (= arg1 1)(= arg2 4)(= arg3 0))
		(botRepr140)
		NIL
	)
	(if (and (= arg1 1)(= arg2 4)(= arg3 1))
		(botRepr141)
		NIL
	)
	(if (and (= arg1 1)(= arg2 4)(= arg3 2))
		(botRepr142)
		NIL
	)
	;;
	;;
	;;
	;;
	;;
	;;
	(if (and (= arg1 2)(= arg2 0)(= arg3 0))
		(botRepr200)
		NIL
	)
	(if (and (= arg1 2)(= arg2 0)(= arg3 1))
		(botRepr201)
		NIL
	)
	(if (and (= arg1 2)(= arg2 0)(= arg3 2))
		(botRepr202)
		NIL
	)
	(if (and (= arg1 2)(= arg2 1)(= arg3 0))
		(botRepr210)
		NIL
	)
	(if (and (= arg1 2)(= arg2 1)(= arg3 1))
		(botRepr211)
		NIL
	)
	(if (and (= arg1 2)(= arg2 1)(= arg3 2))
		(botRepr212)
		NIL
	)
	(if (and (= arg1 2)(= arg2 2)(= arg3 0))
		(botRepr220)
		NIL
	)
	(if (and (= arg1 2)(= arg2 2)(= arg3 1))
		(botRepr221)
		NIL
	)
	(if (and (= arg1 2)(= arg2 2)(= arg3 2))
		(botRepr222)
		NIL
	)
	(if (and (= arg1 2)(= arg2 3)(= arg3 0))
		(botRepr230)
		NIL
	)
	(if (and (= arg1 2)(= arg2 3)(= arg3 1))
		(botRepr231)
		NIL
	)
	(if (and (= arg1 2)(= arg2 3)(= arg3 2))
		(botRepr232)
		NIL
	)
	(if (and (= arg1 2)(= arg2 4)(= arg3 0))
		(botRepr240)
		NIL
	)
	(if (and (= arg1 2)(= arg2 4)(= arg3 1))
		(botRepr241)
		NIL
	)
	(if (and (= arg1 2)(= arg2 4)(= arg3 2))
		(botRepr242)
		NIL
	)
	;;
	;;
	;;
	;;
	;;
	;;
	(if (and (= arg1 3)(= arg2 0)(= arg3 0))
		(botRepr300)
		NIL
	)
	(if (and (= arg1 3)(= arg2 0)(= arg3 1))
		(botRepr301)
		NIL
	)
	(if (and (= arg1 3)(= arg2 0)(= arg3 2))
		(botRepr302)
		NIL
	)
	(if (and (= arg1 3)(= arg2 1)(= arg3 0))
		(botRepr310)
		NIL
	)
	(if (and (= arg1 3)(= arg2 1)(= arg3 1))
		(botRepr311)
		NIL
	)
	(if (and (= arg1 3)(= arg2 1)(= arg3 2))
		(botRepr312)
		NIL
	)
	(if (and (= arg1 3)(= arg2 2)(= arg3 0))
		(botRepr320)
		NIL
	)
	(if (and (= arg1 3)(= arg2 2)(= arg3 1))
		(botRepr321)
		NIL
	)
	(if (and (= arg1 3)(= arg2 2)(= arg3 2))
		(botRepr322)
		NIL
	)
	(if (and (= arg1 3)(= arg2 3)(= arg3 0))
		(botRepr330)
		NIL
	)
	(if (and (= arg1 3)(= arg2 3)(= arg3 1))
		(botRepr331)
		NIL
	)
	(if (and (= arg1 3)(= arg2 3)(= arg3 2))
		(botRepr332)
		NIL
	)
	(if (and (= arg1 3)(= arg2 4)(= arg3 0))
		(botRepr340)
		NIL
	)
	(if (and (= arg1 3)(= arg2 4)(= arg3 1))
		(botRepr341)
		NIL
	)
	(if (and (= arg1 3)(= arg2 4)(= arg3 2))
		(botRepr342)
		NIL
	)
	;;
	;;
	;;
	;;
	;;
	;;
	(if (and (= arg1 4)(= arg2 0)(= arg3 0))
		(botRepr400)
		NIL
	)
	(if (and (= arg1 4)(= arg2 0)(= arg3 1))
		(botRepr401)
		NIL
	)
	(if (and (= arg1 4)(= arg2 0)(= arg3 2))
		(botRepr402)
		NIL
	)
	(if (and (= arg1 4)(= arg2 1)(= arg3 0))
		(botRepr410)
		NIL
	)
	(if (and (= arg1 4)(= arg2 1)(= arg3 1))
		(botRepr411)
		NIL
	)
	(if (and (= arg1 4)(= arg2 1)(= arg3 2))
		(botRepr412)
		NIL
	)
	(if (and (= arg1 4)(= arg2 2)(= arg3 0))
		(botRepr420)
		NIL
	)
	(if (and (= arg1 4)(= arg2 2)(= arg3 1))
		(botRepr421)
		NIL
	)
	(if (and (= arg1 4)(= arg2 2)(= arg3 2))
		(botRepr422)
		NIL
	)
	(if (and (= arg1 4)(= arg2 3)(= arg3 0))
		(botRepr430)
		NIL
	)
	(if (and (= arg1 4)(= arg2 3)(= arg3 1))
		(botRepr431)
		NIL
	)
	(if (and (= arg1 4)(= arg2 3)(= arg3 2))
		(botRepr432)
		NIL
	)
	(if (and (= arg1 4)(= arg2 4)(= arg3 0))
		(botRepr440)
		NIL
	)
	(if (and (= arg1 4)(= arg2 4)(= arg3 1))
		(botRepr441)
		NIL
	)
	(if (and (= arg1 4)(= arg2 4)(= arg3 2))
		(botRepr442)
		NIL
	)
	;;
	;;
	;;
	;;
	;;
	;;
	(if (and (= arg1 5)(= arg2 0)(= arg3 0))
		(botRepr500)
		NIL
	)
	(if (and (= arg1 5)(= arg2 0)(= arg3 1))
		(botRepr501)
		NIL
	)
	(if (and (= arg1 5)(= arg2 0)(= arg3 2))
		(botRepr502)
		NIL
	)
	(if (and (= arg1 5)(= arg2 1)(= arg3 0))
		(botRepr510)
		NIL
	)
	(if (and (= arg1 5)(= arg2 1)(= arg3 1))
		(botRepr511)
		NIL
	)
	(if (and (= arg1 5)(= arg2 1)(= arg3 2))
		(botRepr512)
		NIL
	)
	(if (and (= arg1 5)(= arg2 2)(= arg3 0))
		(botRepr520)
		NIL
	)
	(if (and (= arg1 5)(= arg2 2)(= arg3 1))
		(botRepr521)
		NIL
	)
	(if (and (= arg1 5)(= arg2 2)(= arg3 2))
		(botRepr522)
		NIL
	)
	(if (and (= arg1 5)(= arg2 3)(= arg3 0))
		(botRepr530)
		NIL
	)
	(if (and (= arg1 5)(= arg2 3)(= arg3 1))
		(botRepr531)
		NIL
	)
	(if (and (= arg1 5)(= arg2 3)(= arg3 2))
		(botRepr532)
		NIL
	)
	(if (and (= arg1 5)(= arg2 4)(= arg3 0))
		(botRepr540)
		NIL
	)
	(if (and (= arg1 5)(= arg2 4)(= arg3 1))
		(botRepr541)
		NIL
	)
	(if (and (= arg1 5)(= arg2 4)(= arg3 2))
		(botRepr542)
		NIL
	)
	;;
	;;
	;;
	;;
	;;
	;;
	(if (and (= arg1 6)(= arg2 0)(= arg3 0))
		(botRepr600)
		NIL
	)
	(if (and (= arg1 6)(= arg2 0)(= arg3 1))
		(botRepr601)
		NIL
	)
	(if (and (= arg1 6)(= arg2 0)(= arg3 2))
		(botRepr602)
		NIL
	)
	(if (and (= arg1 6)(= arg2 1)(= arg3 0))
		(botRepr610)
		NIL
	)
	(if (and (= arg1 6)(= arg2 1)(= arg3 1))
		(botRepr611)
		NIL
	)
	(if (and (= arg1 6)(= arg2 1)(= arg3 2))
		(botRepr612)
		NIL
	)
	(if (and (= arg1 6)(= arg2 2)(= arg3 0))
		(botRepr620)
		NIL
	)
	(if (and (= arg1 6)(= arg2 2)(= arg3 1))
		(botRepr621)
		NIL
	)
	(if (and (= arg1 6)(= arg2 2)(= arg3 2))
		(botRepr622)
		NIL
	)
	(if (and (= arg1 6)(= arg2 3)(= arg3 0))
		(botRepr630)
		NIL
	)
	(if (and (= arg1 6)(= arg2 3)(= arg3 1))
		(botRepr631)
		NIL
	)
	(if (and (= arg1 6)(= arg2 3)(= arg3 2))
		(botRepr632)
		NIL
	)
	(if (and (= arg1 6)(= arg2 4)(= arg3 0))
		(botRepr640)
		NIL
	)
	(if (and (= arg1 6)(= arg2 4)(= arg3 1))
		(botRepr641)
		NIL
	)
	(if (and (= arg1 6)(= arg2 4)(= arg3 2))
		(botRepr642)
		NIL
	)
	;;
	;;
	;;
	;;
	;;
	;;
	(if (and (= arg1 7)(= arg2 0)(= arg3 0))
		(botRepr700)
		NIL
	)
	(if (and (= arg1 7)(= arg2 0)(= arg3 1))
		(botRepr701)
		NIL
	)
	(if (and (= arg1 7)(= arg2 0)(= arg3 2))
		(botRepr702)
		NIL
	)
	(if (and (= arg1 7)(= arg2 1)(= arg3 0))
		(botRepr710)
		NIL
	)
	(if (and (= arg1 7)(= arg2 1)(= arg3 1))
		(botRepr711)
		NIL
	)
	(if (and (= arg1 7)(= arg2 1)(= arg3 2))
		(botRepr712)
		NIL
	)
	(if (and (= arg1 7)(= arg2 2)(= arg3 0))
		(botRepr720)
		NIL
	)
	(if (and (= arg1 7)(= arg2 2)(= arg3 1))
		(botRepr721)
		NIL
	)
	(if (and (= arg1 7)(= arg2 2)(= arg3 2))
		(botRepr722)
		NIL
	)
	(if (and (= arg1 7)(= arg2 3)(= arg3 0))
		(botRepr730)
		NIL
	)
	(if (and (= arg1 7)(= arg2 3)(= arg3 1))
		(botRepr731)
		NIL
	)
	(if (and (= arg1 7)(= arg2 3)(= arg3 2))
		(botRepr732)
		NIL
	)
	(if (and (= arg1 7)(= arg2 4)(= arg3 0))
		(botRepr740)
		NIL
	)
	(if (and (= arg1 7)(= arg2 4)(= arg3 1))
		(botRepr741)
		NIL
	)
	(if (and (= arg1 7)(= arg2 4)(= arg3 2))
		(botRepr742)
		NIL
	)
)

;;(ifFunction 5 3 1)